### ISSUE TITLE
[thegraph] yarn codegen-raw: error Command failed with exit code 1

### ISSUE THREAD

**Issue by Decentralisedme** [aave/aave-protocol#39] opened 2021-01-09 16:54 UTC
Hello Aave,
Inside the thegraph directory,  when I run the following: yarn codegen-raw:
```
yarn run v1.22.10
$ TYPE=raw npm run prepare && graph codegen --output-dir ./raw/generated
npm WARN lifecycle The node binary used for scripts is /var/folders/nv/ztjvfck52z74nr526shd5kzw0000gn/T/yarn--1610207854304-0.6707123665558101/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> aave-protocol-subgraph@1.0.0 prepare /Users/riccardoanacar/TheGraph/aave_graph/aave-protocol/thegraph
> mustache ./config/${TYPE:-raw}.json ./config/${NETWORK:-dev}.json | mustache  - subgraph.template.yaml > subgraph.yaml

  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✖ Failed to load subgraph from subgraph.yaml: Error in subgraph.yaml:

  Path: dataSources > 1 > mapping > abis > 0 > file
  File does not exist: ../build/contracts/LendingPoolAddressesProviderRegistry.json

Path: dataSources > 2 > mapping > abis > 2 > file
  File does not exist: ../build/contracts/IExtendedPriceAggregator.json

  Path: dataSources > 3 > mapping > abis > 0 > file
  File does not exist: ../build/contracts/ChainlinkUSDETHOracleI.json

  Path: templates > 6 > mapping > abis > 0 > file
  File does not exist: ../build/contracts/IExtendedPriceAggregator.json

  Path: templates > 7 > mapping > abis > 0 > file
  File does not exist: ../build/contracts/IUniswapExchange.json
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Would you be able to give me some directions how to fix this error? are these missing files available? For example:
 - File does not exist: ../build/contracts/IUniswapExchange.json - could IUniswapExchange.json copied in contracts dir?
 Thank you in advance for your help

**Comment by kyzia551** [comment] 2021-01-22 08:22
Duplicate of https://github.com/aave/aave-protocol/issues/24

**Closed by kyzia551** 2021-01-22 08:22 UTC
